#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Search and terminate the process using pkill
pkill -f "4-to_infinity_and_beyond"

if [[ $? -eq 0 ]]; then
    echo "Process terminated"
else
    echo "Process not running"
fi
